// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjNWcOKWJkV--HEAKGaCo4x7RT2gcOI5c',
    appId: '1:455737909200:web:49fae6e02d6a7d3e3ce3d5',
    messagingSenderId: '455737909200',
    projectId: 'salarysoft-f8742',
    authDomain: 'salarysoft-f8742.firebaseapp.com',
    storageBucket: 'salarysoft-f8742.appspot.com',
    measurementId: 'G-M2T9JZQ0NL',
    databaseURL: 'https://salarysoft-f8742-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9G3xe9FLii52mnatXzQh2bsyp9-vS7CI',
    appId: '1:455737909200:android:85220c87ae4ecf6d3ce3d5',
    messagingSenderId: '455737909200',
    projectId: 'salarysoft-f8742',
    storageBucket: 'salarysoft-f8742.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz0rXPEncL7EXkRdpyri-rgtdilVjRdMk',
    appId: '1:455737909200:ios:899ca84e297575c33ce3d5',
    messagingSenderId: '455737909200',
    projectId: 'salarysoft-f8742',
    storageBucket: 'salarysoft-f8742.appspot.com',
    iosBundleId: 'com.example.salarySoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz0rXPEncL7EXkRdpyri-rgtdilVjRdMk',
    appId: '1:455737909200:ios:899ca84e297575c33ce3d5',
    messagingSenderId: '455737909200',
    projectId: 'salarysoft-f8742',
    storageBucket: 'salarysoft-f8742.appspot.com',
    iosBundleId: 'com.example.salarySoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjNWcOKWJkV--HEAKGaCo4x7RT2gcOI5c',
    appId: '1:455737909200:web:c318a6062909c8d83ce3d5',
    messagingSenderId: '455737909200',
    projectId: 'salarysoft-f8742',
    authDomain: 'salarysoft-f8742.firebaseapp.com',
    storageBucket: 'salarysoft-f8742.appspot.com',
    measurementId: 'G-6L8NYJFRW7',
  );
}
